name: 🚀 Deploy AJF Application
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    name: 🚢 Deploy AJF Application
    runs-on: ubuntu-latest
    steps:
      - name: 🚀Checkout code
        uses: actions/checkout@v4
      - name: 📂Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: "${{ secrets.VM_USERNAME }}"
          key: "${{ secrets.VM_SSH_KEY }}"
          port: ${{ secrets.VM_PASSWORD }}
          source: ./
          target: ./Anugerah-Jaya-Farm-Volare

      - name: 🖥️ Deploy PMSxGUM Application to Remote VM
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.VM_HOST }}"
          username: "${{ secrets.VM_USERNAME }}"
          key: "${{ secrets.VM_SSH_KEY }}"
          port: "${{ secrets.VM_SSH_PORT }}"
          script: |
            sudo su
            cd ./Anugerah-Jaya-Farm-Volare
            make compose-down
            make compose-up
