name: 🚀 Deploy AJF Application
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    name: 🚢 Deploy AJF Application
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Copy files to Remote VM via SCP
        uses: appleboy/scp-action@master
        with:
          host: "${{ secrets.VM_HOST }}"
          username: "${{ secrets.VM_USERNAME }}"
          password: "${{ secrets.VM_PASSWORD }}"
          key: "${{ secrets.VM_PRIVATE_KEY }}"
          port: "${{ secrets.VM_SSH_PORT }}"
          source: "."
          target: "./Anugerah-Jaya-Farm-Volare"

      - name: 🖥️ Run compose up on Remote VM
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.VM_HOST }}"
          username: "${{ secrets.VM_USERNAME }}"
          password: "${{ secrets.VM_PASSWORD }}"
          key: "${{ secrets.VM_PRIVATE_KEY }}"
          port: "${{ secrets.VM_SSH_PORT }}"
          timeout: 60m
          command_timeout: 60m
          script: |
            cd ./Anugerah-Jaya-Farm-Volare
            make compose-down
            make compose-up
