name: 🚀 Deploy AJF Application
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    name: 🚢 Deploy AJF Application
    runs-on: ubuntu-latest
    steps:
      - name: 🛒Checkout code
        uses: actions/checkout@v4
      - name: 🖥️ Deploy PMSxGUM Application to Remote VM
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.VM_HOST }}"
          username: "${{ secrets.VM_USERNAME }}"
          password: "${{ secrets.VM_PASSWORD }}"
          port: "${{ secrets.VM_SSH_PORT }}"
          timeout: 60m
          command_timeout: 60m
          script: |
            cd ./Anugerah-Jaya-Farm-Volare
            git pull origin master
            make compose-down
            make compose-up
